feat: Add Comments To PaymentFrequencie, Reference And Relatioship Re…
AcrossTec/SysCredit pull request #107
Opened 2023-10-18 16:17 UTC by LaelMedina

2023-10-18 17:46 UTC, KaimDev requested changes

2023-10-18 17:46 UTC, KaimDev commented on SysCredit.Api/Requests/PaymentFrequencies/DeletePaymentFrequencyRequest.cs
>      public long PaymentFrequencyId { get; set; }
Comentar la propiedad

2023-10-18 17:46 UTC, KaimDev commented on SysCredit.Api/Requests/References/CreateReferenceRequest.cs
>  public class CreateReferenceRequest : IRequest
Comentar sus propiedades

2023-10-18 17:46 UTC, KaimDev commented on SysCredit.Api/Requests/Relationships/CreateRelationshipRequest.cs
>  public class CreateRelationshipRequest : IRequest
Comentar sus propiedades

2023-10-18 17:46 UTC, KaimDev commented on SysCredit.Api/Requests/Relationships/DeleteRelationshipRequest.cs
>  public class DeleteRelationshipRequest : IRequest
Comentar sus propiedadse

2023-10-18 17:46 UTC, KaimDev commented on SysCredit.Api/Requests/Relationships/UpdateRelationshipRequest.cs
>  public class UpdateRelationshipRequest : IRequest
Comentar sus propiedades

2023-10-19 16:19 UTC, kenthLol commented on SysCredit.Api/Requests/Relationships/CreateRelationshipRequest.cs
> +///     Request para crear una relacion
Que se cambiar la palabra Relación por Parentesco

2023-10-19 16:20 UTC, kenthLol commented on SysCredit.Api/Requests/Relationships/DeleteRelationshipRequest.cs
> +///     Request para borrar una relacion
Cambiar la palabra Relación por Parentesco

2023-10-19 16:20 UTC, kenthLol commented on SysCredit.Api/Requests/Relationships/DeleteRelationshipRequest.cs
> +    ///     Propiedad que representa el Id de la relacion
Cambiar la palabra Relación por Parentesco

2023-10-19 16:20 UTC, kenthLol commented on SysCredit.Api/Requests/Relationships/UpdateRelationshipRequest.cs
> +///     Request para actualizar una relacion
Cambiar la palabra Relación por Parentesco

2023-10-19 16:21 UTC, kenthLol commented on SysCredit.Api/Requests/Relationships/UpdateRelationshipRequest.cs
> +    ///     Propiedad que representa el Id de la relacion
Cambiar la palabra Relación por Parentesco

2023-10-19 16:21 UTC, kenthLol commented on SysCredit.Api/Requests/Relationships/UpdateRelationshipRequest.cs
> +    ///     Propiedad que representa el nombre de la relacion
Cambiar la palabra Relación por Parentesco

2023-10-19 16:25 UTC, kenthLol requested changes

2023-10-19 16:25 UTC, kenthLol commented on SysCredit.Api/Requests/Relationships/CreateRelationshipRequest.cs
> +///     Request para crear una relacion
Cambiar la palabra Relación por Parentesco

2023-10-19 16:25 UTC, kenthLol commented on SysCredit.Api/Requests/Relationships/CreateRelationshipRequest.cs
> +    ///     Propiedad que representa el nombre de la relacion
Cambiar la palabra Relación por Parentesco

2023-10-19 16:25 UTC, kenthLol commented on SysCredit.Api/Requests/Relationships/DeleteRelationshipRequest.cs
> +///     Request para borrar una relacion
Cambiar la palabra Relación por Parentesco

2023-10-19 16:25 UTC, kenthLol commented on SysCredit.Api/Requests/Relationships/DeleteRelationshipRequest.cs
> +    ///     Propiedad que representa el Id de la relacion
Cambiar la palabra Relación por Parentesco

2023-10-19 16:25 UTC, kenthLol commented on SysCredit.Api/Requests/Relationships/UpdateRelationshipRequest.cs
> +///     Request para actualizar una relacion
Cambiar la palabra Relación por Parentesco

2023-10-19 16:25 UTC, kenthLol commented on SysCredit.Api/Requests/Relationships/UpdateRelationshipRequest.cs
> +    ///     Propiedad que representa el Id de la relacion
Cambiar la palabra Relación por Parentesco

2023-10-19 16:25 UTC, kenthLol commented on SysCredit.Api/Requests/Relationships/UpdateRelationshipRequest.cs
> +    ///     Propiedad que representa el nombre de la relacion
Cambiar la palabra Relación por Parentesco

2023-10-19 17:04 UTC, closed without merging