feat: Add Commets to Customer and Authentication Validator
AcrossTec/SysCredit pull request #111
Opened 2023-10-19 17:27 UTC by SoulCrow23

2023-10-19 21:51 UTC, KaimDev requested changes

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Requests/Customers/CustomerGuarantorRequest.cs
> +///     Clase que representa una solicitud de garantía de cliente.
Mejorar el comentario

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Requests/Customers/CustomerIdRequest.cs
>      /// <param name="CustomerId">Id del cliente</param>
Enter

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Requests/Customers/CustomerIdRequest.cs
>      /// <param name="Request">Objecto de tipo CustomerIdRequest</param>
Enter

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Authentications/Roles/AsyncExistRoleNameValidator.cs
> +///     Clase Validadora del Request que Revisa si Existe El Nombre del Rol.
Poner `<see>`

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueEmailValidator.cs
> +/// <typeparam name="T">Tipo de Store</typeparam>
enter

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueEmailValidator.cs
> +    ///     Verifica si Existe el Email en otros Clientes
punto

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueEmailValidator.cs
> +    /// <param name="Context">Contiene Informacion del Request que se esta validado</param>
Agregar acentos, enter y punto final

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueEmailValidator.cs
> +    /// <param name="Email">Id dek Cliente que se esta valdiadndo</param>
Corregir ortografia, enter y punto final

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueEmailValidator.cs
> +    /// <param name="Cancellation">Metodp que permite detener la Validacion </param>
Ortografia, enter y punto final

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueEmailValidator.cs
> +    /// <returns>Retorna Un valor booleano que indica si el cliente tiene un Email unico</returns>
enter y cambiar mensaje: `Retorna true si el email del cliente es unico`

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueEmailValidator.cs
> +    ///     Retorna El mensaje de Error.
`Lanza el error del validador`

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueEmailValidator.cs
> +    /// <param name="ErrorCode">Codigo de Error asignado </param>
Enter y punto final

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueEmailValidator.cs
> +    /// <returns>Retorna una cadena de texto que contiene el mensaje de error.</returns>
Enter
y cambiar mensaje: `Retorna el mensaje de error`

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueIdentificationValidator.cs
> +    ///     Valida si el Cliente Tiene Una Identificación Unica
punto final

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueIdentificationValidator.cs
> +    /// <param name="Context">Contiene informacion del Request que se va a Validar</param>
Punto final y enter

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueIdentificationValidator.cs
> +    /// <param name="Identification">Identificacipn del Cliente que se va a Validar </param>
ortografia y punto final

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueIdentificationValidator.cs
> +    ///     Retorna el mensaje de Error
`Lanza el error del validador`

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueIdentificationValidator.cs
> +    /// <returns>Retorna una cadena de texto que contiene el mensaje de error.</returns>
`Retorna el mensaje de error`

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueIdentificationValidator.cs
> +    ///     Nombre del Validador
punto final

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniquePhoneValidator.cs
> +///     Validador que verifica si el Cliente tiene un Unico Numero de Telefono.
falta acentos

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniquePhoneValidator.cs
> +/// <typeparam name="T">Tipo de Request a Validar</typeparam>
enter

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniquePhoneValidator.cs
> +    /// <param name="Cancellation">Metodo que detiene la Validacion</param>
Acentos, Enter y punto final

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniquePhoneValidator.cs
> +    /// <returns>Devuelve un valor booleano que indica si el número de teléfono es único (verdadero) o no (falso).</returns>
`Retorna true si el numero de telefono es unico`

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniquePhoneValidator.cs
> +    ///     Retorna el mensaje de Error.
Lanza el error del validador

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Authentications/Users/AsyncUserUniquePhoneValidator.cs
> +    ///     Retorna el mensaje de Error.
`Lanza el error del validador`

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Authentications/Users/AsyncUserUniquePhoneValidator.cs
> +    /// <returns>Retorna una cadena de texto que contiene el mensaje de error.</returns>
`Retorna el mensaje de error`

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Authentications/Users/AsyncUserUniqueUserNameValidator.cs
> +    ///     Retorna el mensaje de Error
`Lanza el error del validador`

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Authentications/Users/AsyncUserUniqueUserNameValidator.cs
> +    /// <returns>Retorna una cadena de texto que contiene el mensaje de error.</returns>
Agregar punto final y enter

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Authentications/Users/AsyncUserUniqueUserNameValidator.cs
> +    /// <returns>Retorna una cadena de texto que contiene el mensaje de error.</returns>
`Retorna el mensaje de error`

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Authentications/Users/AsyncUserUniqueUserNameValidator.cs
> +    ///     Nombre del Validador
Punto final

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Authentications/Users/TokenRequestValidator.cs
> +    ///     Valida la contraseña y el Email.<see cref="TokenRequestValidator"/>
Punto final

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Authentications/Users/TokenRequestValidator.cs
> +///     Clase Validadora de <see cref="TokenRequestValidator"/>
Punto final

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Authentications/Users/AsyncUserUniqueEmailValidator.cs
> +    ///     Retorna el mensaje de Error.
`Lanza el error del validador`

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Authentications/Users/AsyncUserUniqueEmailValidator.cs
> +    /// <returns>Retorna una cadena de texto que contiene el mensaje de error.</returns>
Enter
`Retorna el mensaje de error`

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueIdentificationValidator.cs
> +///     Validador que verifica si la Identificacion del Cliente es Unica.
Acento

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueIdentificationValidator.cs
> +/// <typeparam name="T">Tipo de Request a Validar</typeparam>
punto final

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueIdentificationValidator.cs
> +    /// <returns>Retorna Un valor booleano que indica si el cliente tiene una identificacion unica</returns>
enter, punto final y ortografia
`Retorna true si la identificación es unica`

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniqueIdentificationValidator.cs
> +    /// <param name="ErrorCode">Codigo de Error Asignado</param>
punto y enter

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncCustomerUniquePhoneValidator.cs
> +    /// <returns>Retorna una cadena de texto que contiene el mensaje de error.</returns>
`Retorna el mensaje de error`

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncVerifyIfCustomerExistsByIdValidator.cs
> +    /// <returns>Un valor booleano que indica si el cliente existe</returns>
`Retorna true si el cliente existe.`

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncVerifyIfCustomerExistsByIdValidator.cs
>      /// <param name="Cancellation">Permite cancelar la validación en un proceso asincrono</param>
Punto final y enter

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncVerifyifCustomerByGuarantorIdValidator.cs
> +///     Validador que verifica si un Customer Usa un fiador.
Validador que verifica si un cliente tiene un fiador.

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncVerifyifCustomerByGuarantorIdValidator.cs
> +/// <typeparam name="T"> Tipo del Request que se Va a validar</typeparam>
punto y enter

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncVerifyifCustomerByGuarantorIdValidator.cs
> +    /// <param name="Cancellation"> Metodo que detiene la Validacion</param>
Acentos, punto final, ortografia y enter

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncVerifyifCustomerByGuarantorIdValidator.cs
> +    /// <returns>Devuelve `true` si el Cliente no tiene un Fiador asignado, de lo contrario, devuelve `false`.</returns>
Retorna true si el cliente no tiene un fiador por el id del fiador

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncVerifyifCustomerByGuarantorIdValidator.cs
> +    ///     Retorna la el mensaje de Error.
Lanza el error del validador.

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncVerifyifCustomerByGuarantorIdValidator.cs
> +    /// <param name="ErrorCode">Codigo de Error adignado</param>
ortografia, punto final y enter

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncVerifyifCustomerByGuarantorIdValidator.cs
> +        return base.GetDefaultMessageTemplate(ErrorCode);
ErrorCodeMessages.GetMessageFromCode(ErrorCode)!;

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/AsyncVerifyifCustomerByGuarantorIdValidator.cs
> +    /// <returns>Retorna una cadena de texto que contiene el mensaje de error.</returns>
Retorna el mensaje de error

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/CreateCustomerValidator.cs
> +///     Validador del <see cref="CreateCustomerValidator"/>
punto final

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/CreateCustomerValidator.cs
> +    ///     Se establecen las Reglas para Validar <see cref="CreateCustomerValidator"/>
punto final

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/CustomerGuarantorValidator.cs
> +    ///     Se establecen las reglas para validar el <see cref="CustomerGuarantorValidator"/>
.

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/CustomerGuarantorsUniqueInRequestValidator.cs
> +    /// <param name="Context">Obtiene el Objeto donde fue usado el Validador </param>
punto y enter

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/CustomerGuarantorsUniqueInRequestValidator.cs
> +    /// <param name="GuarantorRequests">Una peticion de Fiadores por Clientes </param>
punto y enter

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/CustomerGuarantorsUniqueInRequestValidator.cs
> +    /// <returns>Retorna una cadena de texto que contiene el mensaje de error.</returns>
enter
`Retorna el mensaje de error`

2023-10-19 21:51 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/CustomerGuarantorsUniqueInRequestValidator.cs
> +    ///     Retorna el mensaje de Error.
Lanza el error del validador

2023-10-20 16:02 UTC, KaimDev approved these changes

2023-10-20 16:03 UTC, kenthLol approved these changes

2023-10-20 16:06 UTC, merged