feat: Add Foreign Keys to CustomerReference and CustomerGuarantor Table
AcrossTec/SysCredit pull request #130
Opened 2023-10-25 22:07 UTC by dayanaloiretgonzalez

2023-10-25 22:37 UTC, KaimDev requested changes

2023-10-25 22:37 UTC, KaimDev commented on SysCredit.SQLServer/Tables/CustomerGuarantor.sql
> +    CONSTRAINT [FK_CustomerGuarantor_LoanId_Loan_LoanId]                         FOREIGN KEY ([LoanId])         REFERENCES [Loan]([LoanId]),
Para que se vea ordenado poner la FK de LoanId encima del CONSTRAINT UNIQUE

2023-10-25 22:59 UTC, KaimDev approved these changes

2023-10-26 16:01 UTC, kenthLol approved these changes

2023-10-26 16:14 UTC, merged