feat: add error codes to Loantype Guarantor and customer
AcrossTec/SysCredit pull request #155
Opened 2023-11-07 20:56 UTC by SoulCrow23

Códigos de errores
LoanType

2023-11-08 21:20 UTC, KaimDev requested changes

2023-11-08 21:20 UTC, KaimDev commented on SysCredit.Api/Properties/ErrorCodeMessages.es-NI.resx
> +    <value>El Cliente tiene en uso este Fiador</value>
Cambiar `El` por `Un`

2023-11-08 21:20 UTC, KaimDev commented on SysCredit.Api/Properties/ErrorCodeMessages.es-NI.resx
> +    <value>El Cèlular {0} no tiene un valor valido</value>
Arreglar tilde invertida

2023-11-08 21:20 UTC, KaimDev commented on SysCredit.Api/Properties/ErrorCodeMessages.resx
> +  <data name="String2" xml:space="preserve">
No es valido este codigo de error

2023-11-08 21:20 UTC, KaimDev commented on SysCredit.Api/Properties/ErrorCodeMessages.resx
> +  <data name="String" xml:space="preserve">
No es valido este codigo de error

2023-11-08 21:20 UTC, KaimDev commented on SysCredit.Api/Properties/ErrorCodeMessages.resx
> +  <data name="String1" xml:space="preserve">
No es valido este codigo de error

2023-11-08 21:20 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/CustomerGuarantorValidator.cs
> +            .WithName(GetMessage("Relationship")!);
El mensaje general debe ser "Relationship Id"

2023-11-08 21:20 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/CustomerGuarantorValidator.cs
> +            .WithName(GetMessage("Guarantor")!);
El mensaje general debe ser "Guarantor Id"

2023-11-08 21:20 UTC, KaimDev commented on SysCredit.Api/Validations/Customers/CustomerIdRequestValidator.cs
> +            .WithName(GetMessage("Customer"));
El mensaje general debe ser "Customer Id"

2023-11-08 21:20 UTC, KaimDev commented on SysCredit.Api/Validations/Guarantors/DeleteGuarantorValidator.cs
> +            .WithName(GetMessage("Guarantor")!);
El mensaje general debe ser "Guarantor Id"

2023-11-08 21:20 UTC, KaimDev commented on SysCredit.Api/Validations/LoanTypes/DeleteLoanTypeValidator.cs
> +            .WithName(GetMessage("LoanType")!);
El mensaje general debe ser "LoanType Id"

2023-11-09 17:44 UTC, kenthLol requested changes

2023-11-09 17:44 UTC, kenthLol commented on SysCredit.Api/Validations/Customers/CreateCustomerValidator.cs
> +            .Phone().WithErrorCode(SERVG0122).WithMessage((Request) => String.Format(GetMessageFromCode(SERVG0122)!, Request.Phone)!)
Corregir el código de error

2023-11-09 17:44 UTC, kenthLol commented on SysCredit.Api/Validations/Guarantors/CreateGuarantorValidator.cs
> +            .WithName(GetMessage("Identification"));
Cambiar cada nombre de mensaje a Español. A partir de aquí en adelante

2023-11-09 17:44 UTC, kenthLol commented on SysCredit.Api/Validations/LoanTypes/DeleteLoanTypeValidator.cs
> +            .NotNull().WithErrorCode(SERVLT0101).WithMessage(GetMessageFromCode(SERVLT0105)!)
Corregir los códigos de errores

2023-11-12 18:40 UTC, closed without merging